<a href="https://colab.research.google.com/github/vivek6311/Artificial-Intelligence-with-Python/blob/master/Least_Square_Regression_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
df= pd.read_excel("/content/All_blocks_data.xlsx")
#CVI= pd.read_excel("/content/CVI_data.xlsx")
df.head()

Date       CVI       EVI      EVI2       GLI     GNDVI      NDVI  \
0  Block_3A  3.314836  0.377187  0.629505  0.125957  0.558451  0.577358   
1  Block_3B  3.254148  0.396382  0.656389  0.126742  0.553079  0.573202   
2   Block_6  3.153244  0.361809  0.603965  0.144976  0.561054  0.597163   
3  Block_7a  3.045632  0.257264  0.419152  0.125760  0.532351  0.557745   
4  Block_7b  2.923830  0.221227  0.374607  0.121004  0.509866  0.527424   

       NDWI      SAVI  yield/acer  
0 -0.577358  0.391762  173.165594  
1 -0.573202  0.408655  190.160750  
2 -0.597163  0.370265  166.650522  
3 -0.557745  0.270678  172.325928  
4 -0.527424  0.248608  227.102086

In [4]:
X= df.iloc[:, 1:-1]
#X.columns = X.columns.astype(str)
X

CVI       EVI      EVI2       GLI     GNDVI      NDVI      NDWI  \
0   3.314836  0.377187  0.629505  0.125957  0.558451  0.577358 -0.577358   
1   3.254148  0.396382  0.656389  0.126742  0.553079  0.573202 -0.573202   
2   3.153244  0.361809  0.603965  0.144976  0.561054  0.597163 -0.597163   
3   3.045632  0.257264  0.419152  0.125760  0.532351  0.557745 -0.557745   
4   2.923830  0.221227  0.374607  0.121004  0.509866  0.527424 -0.527424   
5   3.204426  0.362277  0.457999  0.123158  0.558373  0.581141 -0.581141   
6   3.190185  0.391573  0.651457  0.133222  0.558061  0.591349 -0.591349   
7   3.273085  0.360076  0.617187  0.122624  0.552211  0.572445 -0.572445   
8   3.272647  0.408976  0.675797  0.110742  0.542629  0.555171 -0.555171   
9   3.240294  0.409792  0.684137  0.117746  0.549331  0.569460 -0.569460   
10  2.277847  0.290994  0.580120  0.102473  0.484656  0.492902 -0.492902   

        SAVI  
0   0.391762  
1   0.408655  
2   0.370265  
3   0.270678  
4   0.248608  
5   0.287873  
6   0.409882  
7   0.390613  
8   0.436582  
9   0.440015  
10  0.404495

In [ ]:
# X= df.drop(['Date', 'yield/acer','block_Block_7b'], axis='columns')
# X.head()

In [2]:
y= df['yield/acer']
y.head()

0    173.165594
1    190.160750
2    166.650522
3    172.325928
4    227.102086
Name: yield/acer, dtype: float64

In [5]:
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize and fit the PLS regression model
n_components = 1  # Number of components for PLS
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, y_train)

# Predict crop yield on the testing set
y_pred = pls.predict(X_test)

# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)


Mean Squared Error (MSE): 2865.064678186535
R-squared (R2) Score: -2.7650320846036833


In [6]:
import pandas as pd
import statsmodels.api as sm
model = sm.OLS(y, X)
results = model.fit()

# Print the regression results
print(results.summary())


                                 OLS Regression Results                                
Dep. Variable:             yield/acer   R-squared (uncentered):                   0.991
Model:                            OLS   Adj. R-squared (uncentered):              0.975
Method:                 Least Squares   F-statistic:                              62.29
Date:                Tue, 27 Jun 2023   Prob (F-statistic):                    0.000641
Time:                        17:09:34   Log-Likelihood:                         -46.117
No. Observations:                  11   AIC:                                      106.2
Df Residuals:                       4   BIC:                                      109.0
Df Model:                           7                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1736: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=11
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [7]:
print(y_pred)

[[172.30625004]
 [159.0692315 ]
 [158.42874233]
 [224.71231582]]


In [8]:
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and fit the PLS regression model
n_components = 1  # Number of components for PLS
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, y_train)

# Predict crop yield on the testing set
y_pred = pls.predict(X_test)

# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)
model = sm.OLS(y, X)
results = model.fit()

# Print the regression results
print(results.summary())

Mean Squared Error (MSE): 229.12231199183097
R-squared (R2) Score: 0.6889812905636714
                                 OLS Regression Results                                
Dep. Variable:             yield/acer   R-squared (uncentered):                   0.991
Model:                            OLS   Adj. R-squared (uncentered):              0.975
Method:                 Least Squares   F-statistic:                              62.29
Date:                Tue, 27 Jun 2023   Prob (F-statistic):                    0.000641
Time:                        17:10:37   Log-Likelihood:                         -46.117
No. Observations:                  11   AIC:                                      106.2
Df Residuals:                       4   BIC:                                      109.0
Df Model:                           7                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err  

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1736: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=11
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [9]:
import pandas as pd
import statsmodels.api as sm
model = sm.OLS(y, X)
results = model.fit()

# Print the regression results
print(results.summary())

                                 OLS Regression Results                                
Dep. Variable:             yield/acer   R-squared (uncentered):                   0.991
Model:                            OLS   Adj. R-squared (uncentered):              0.975
Method:                 Least Squares   F-statistic:                              62.29
Date:                Tue, 27 Jun 2023   Prob (F-statistic):                    0.000641
Time:                        17:10:54   Log-Likelihood:                         -46.117
No. Observations:                  11   AIC:                                      106.2
Df Residuals:                       4   BIC:                                      109.0
Df Model:                           7                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1736: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=11
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [ ]:
print(y_pred)

[[170.85457241]
 [173.33607864]
 [171.66071471]]


# Partial Least Square Regression on Individual Parameters

In [11]:
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize and fit the PLS regression model
n_components = 1  # Number of components for PLS
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, y_train)

# Predict crop yield on the testing set
y_pred = pls.predict(X_test)

# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)
model = sm.OLS(y, X)
results = model.fit()

# Print the regression results
print(results.summary())

Mean Squared Error (MSE): 2865.064678186535
R-squared (R2) Score: -2.7650320846036833
                                 OLS Regression Results                                
Dep. Variable:             yield/acer   R-squared (uncentered):                   0.991
Model:                            OLS   Adj. R-squared (uncentered):              0.975
Method:                 Least Squares   F-statistic:                              62.29
Date:                Tue, 27 Jun 2023   Prob (F-statistic):                    0.000641
Time:                        17:12:09   Log-Likelihood:                         -46.117
No. Observations:                  11   AIC:                                      106.2
Df Residuals:                       4   BIC:                                      109.0
Df Model:                           7                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err  

/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py:1736: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=11
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


#EVI2

In [12]:
#X = df[ 'CVI'] #, 'EVI', 'EVI2', 'GLI', 'GNDVI', 'NDWI', 'SAVI'
# Separate X and Y variables
X = df['EVI2'].values.reshape(-1, 1)  # Reshape X to a 2D array
Y = df['yield/acer'].values.reshape(-1, 1)  # Reshape Y to a 2D array

# Scale the X and Y variables
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
Y_scaled = scaler.fit_transform(Y)

# Split the data into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y_scaled, test_size=0.2, random_state=42)

# Perform PLS regression
n_components = 1  # Number of PLS components
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, Y_train)

# Predict on the test set
Y_pred = pls.predict(X_test)

# Inverse scale the predicted values
Y_pred_inverse = scaler.inverse_transform(Y_pred)

# Print the predicted values
print("Predicted values:")
print(Y_pred_inverse)
# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)

Predicted values:
[[185.57554937]
 [158.24784725]
 [149.54276781]]
Mean Squared Error (MSE): 2865.064678186535
R-squared (R2) Score: -2.7650320846036833


# GLI

In [13]:
#X = df[ 'CVI'] #, 'EVI', 'EVI2', 'GLI', 'GNDVI', 'NDWI', 'SAVI'
# Separate X and Y variables
X = df['GLI'].values.reshape(-1, 1)  # Reshape X to a 2D array
Y = df['yield/acer'].values.reshape(-1, 1)  # Reshape Y to a 2D array

# Scale the X and Y variables
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
Y_scaled = scaler.fit_transform(Y)

# Split the data into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y_scaled, test_size=0.2, random_state=42)

# Perform PLS regression
n_components = 1  # Number of PLS components
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, Y_train)

# Predict on the test set
Y_pred = pls.predict(X_test)

# Inverse scale the predicted values
Y_pred_inverse = scaler.inverse_transform(Y_pred)

# Print the predicted values
print("Predicted values:")
print(Y_pred_inverse)
# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)

Predicted values:
[[167.02832539]
 [170.2575178 ]
 [160.78571369]]
Mean Squared Error (MSE): 2865.064678186535
R-squared (R2) Score: -2.7650320846036833


# GNDVI

In [14]:
#X = df[ 'CVI'] #, 'EVI', 'EVI2', 'GLI', 'GNDVI', 'NDWI', 'SAVI'
# Separate X and Y variables
X = df['GNDVI'].values.reshape(-1, 1)  # Reshape X to a 2D array
Y = df['yield/acer'].values.reshape(-1, 1)  # Reshape Y to a 2D array

# Scale the X and Y variables
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
Y_scaled = scaler.fit_transform(Y)

# Split the data into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y_scaled, test_size=0.2, random_state=42)

# Perform PLS regression
n_components = 1  # Number of PLS components
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, Y_train)

# Predict on the test set
Y_pred = pls.predict(X_test)

# Inverse scale the predicted values
Y_pred_inverse = scaler.inverse_transform(Y_pred)

# Print the predicted values
print("Predicted values:")
print(Y_pred_inverse)
# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)

Predicted values:
[[169.81247875]
 [169.82134941]
 [168.78645703]]
Mean Squared Error (MSE): 2865.064678186535
R-squared (R2) Score: -2.7650320846036833


# NDWI

In [15]:
#X = df[ 'CVI'] #, 'EVI', 'EVI2', 'GLI', 'GNDVI', 'NDWI', 'SAVI'
# Separate X and Y variables
X = df['NDWI'].values.reshape(-1, 1)  # Reshape X to a 2D array
Y = df['yield/acer'].values.reshape(-1, 1)  # Reshape Y to a 2D array

# Scale the X and Y variables
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
Y_scaled = scaler.fit_transform(Y)

# Split the data into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y_scaled, test_size=0.2, random_state=42)

# Perform PLS regression
n_components = 1  # Number of PLS components
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, Y_train)

# Predict on the test set
Y_pred = pls.predict(X_test)

# Inverse scale the predicted values
Y_pred_inverse = scaler.inverse_transform(Y_pred)

# Print the predicted values
print("Predicted values:")
print(Y_pred_inverse)
# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)

Predicted values:
[[171.10697889]
 [170.48247809]
 [169.17888044]]
Mean Squared Error (MSE): 2865.064678186535
R-squared (R2) Score: -2.7650320846036833


# SAVI

In [16]:
#X = df[ 'CVI'] #, 'EVI', 'EVI2', 'GLI', 'GNDVI', 'NDWI', 'SAVI'
# Separate X and Y variables
X = df['SAVI'].values.reshape(-1, 1)  # Reshape X to a 2D array
Y = df['yield/acer'].values.reshape(-1, 1)  # Reshape Y to a 2D array

# Scale the X and Y variables
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
Y_scaled = scaler.fit_transform(Y)

# Split the data into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y_scaled, test_size=0.2, random_state=42)

# Perform PLS regression
n_components = 1  # Number of PLS components
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, Y_train)

# Predict on the test set
Y_pred = pls.predict(X_test)

# Inverse scale the predicted values
Y_pred_inverse = scaler.inverse_transform(Y_pred)

# Print the predicted values
print("Predicted values:")
print(Y_pred_inverse)
# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)

Predicted values:
[[191.7721469 ]
 [159.90719911]
 [145.10703986]]
Mean Squared Error (MSE): 2865.064678186535
R-squared (R2) Score: -2.7650320846036833


In [17]:
from sklearn.svm import SVR
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the dataset
# df = pd.read_csv('your_dataset.csv')  # Replace 'your_dataset.csv' with the actual file path

# # Separate the features (X) and the target variable (y)
# X = df[['NDVI']].values
# y = df[['yield/acer']].values

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create the SVR model
svr = SVR(kernel='rbf')

# Fit the SVR model to the training data
svr.fit(X_train_scaled, y_train.ravel())

# Predict the crop yield for the test set
y_pred = svr.predict(X_test_scaled)

# Evaluate the model
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print('Mean Squared Error:', mse)
print('R-squared:', r2)


Mean Squared Error: 799.5458777260606
R-squared: -0.08533178136907948
