<a href="https://colab.research.google.com/github/vivek6311/Artificial-Intelligence-with-Python/blob/master/ML_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
A=np.array( [[0.7820,0.7190,0.5210,0.6280,0.8640,0.5630],
[1.0750,0.8780,0.6030,0.9290,1.0630,0.8520],
[1.1250,0.7250,0.4340,1.0860,0.8930,1.0280],
[0.6600,0.7770,0.6130,0.4290,0.9210,0.3540],
[0.3600,0.3080,0.2160,0.3020,0.3710,0.2750],
[1.2270,0.8830,0.5680,1.1300,1.0790,1.0560],
[0.5520,0.3850,0.2430,0.5160,0.4710,0.4840]])


In [ ]:
A

array([[0.782, 0.719, 0.521, 0.628, 0.864, 0.563],
       [1.075, 0.878, 0.603, 0.929, 1.063, 0.852],
       [1.125, 0.725, 0.434, 1.086, 0.893, 1.028],
       [0.66 , 0.777, 0.613, 0.429, 0.921, 0.354],
       [0.36 , 0.308, 0.216, 0.302, 0.371, 0.275],
       [1.227, 0.883, 0.568, 1.13 , 1.079, 1.056],
       [0.552, 0.385, 0.243, 0.516, 0.471, 0.484]])

In [ ]:
u,s, v= np.linalg.svd(A)

In [ ]:
v=v.T
v

array([[-0.48442184, -0.38308146, -0.2591655 , -0.42580257, -0.46472818,
        -0.39260312],
       [-0.16059866,  0.38933784,  0.43998183, -0.44663438,  0.42895582,
        -0.4955348 ],
       [-0.62649115, -0.38363632, -0.01603745,  0.3049619 ,  0.59270683,
         0.12558531],
       [-0.03888381,  0.43209899, -0.83925185, -0.14686162,  0.29294352,
        -0.00711374],
       [-0.49830556,  0.57509402,  0.09600182,  0.50105104, -0.39040238,
        -0.09097216],
       [ 0.31182048, -0.19247116, -0.15947422,  0.50357489,  0.10243688,
        -0.75908487]])

In [ ]:
#print(u)
np.around([u], decimals=2)

array([[[-0.35,  0.3 ,  0.24, -0.18, -0.08, -0.73, -0.39],
        [-0.47,  0.08,  0.42,  0.68,  0.29,  0.08,  0.23],
        [-0.46, -0.49, -0.36,  0.14,  0.02,  0.19, -0.6 ],
        [-0.32,  0.76, -0.26, -0.17,  0.  ,  0.47, -0.1 ],
        [-0.16,  0.07, -0.71,  0.3 , -0.16, -0.41,  0.43],
        [-0.52, -0.26,  0.21, -0.39, -0.53,  0.14,  0.42],
        [-0.23, -0.15, -0.13, -0.47,  0.78, -0.1 ,  0.26]]])

In [ ]:
np.around([s], decimals=3)
print(s)

[4.79578924e+00 6.53591704e-01 8.89568036e-04 6.17694732e-04
 3.93943309e-04 3.31942081e-04]


In [ ]:
s_prime = np.zeros(s.shape[0])

In [ ]:
r = 5
s_prime[:r]=s[:r]

In [ ]:
s_prime

array([4.79578924e+00, 6.53591704e-01, 8.89568036e-04, 6.17694732e-04,
       3.93943309e-04, 0.00000000e+00])

In [ ]:
rank_1= u @ (s_prime * np.eye(7,6)) @ v

In [ ]:
rank_1

array([[0.78207593, 0.71895313, 0.52096117, 0.62812262, 0.86402494,
        0.56281516],
       [1.07499203, 0.87800492, 0.60300407, 0.92898714, 1.06299738,
        0.85201939],
       [1.12498009, 0.72501229, 0.43401018, 1.08596785, 0.89299346,
        1.02804847],
       [0.65995146, 0.77702996, 0.61302483, 0.4289216 , 0.92098405,
        0.35411817],
       [0.36004266, 0.30797367, 0.21597818, 0.3020689 , 0.37101402,
        0.27489614],
       [1.22698574, 0.8830088 , 0.56800729, 1.12997697, 1.07899532,
        1.05603471],
       [0.55201041, 0.38499357, 0.24299467, 0.51601682, 0.47100342,
        0.48397465]])

In [ ]:
print(v)

[[-0.48442184 -0.16059866 -0.62649115 -0.03888381 -0.49830556  0.31182048]
 [-0.38308146  0.38933784 -0.38363632  0.43209899  0.57509402 -0.19247116]
 [-0.2591655   0.43998183 -0.01603745 -0.83925185  0.09600182 -0.15947422]
 [-0.42580257 -0.44663438  0.3049619  -0.14686162  0.50105104  0.50357489]
 [-0.46472818  0.42895582  0.59270683  0.29294352 -0.39040238  0.10243688]
 [-0.39260312 -0.4955348   0.12558531 -0.00711374 -0.09097216 -0.75908487]]


In [ ]:
pd.Series(s)

0    4.795789
1    0.653592
2    0.000890
3    0.000618
4    0.000394
5    0.000332
dtype: float64

Question-2

In [ ]:
B= np.array([[4.4300, 2.9200, 3.6800, 3.9300, 3.4200, 4.0500, 3.3000],
[1.5800, 1.9300, 1.7600, 1.7000, 1.8200, 1.6700, 1.8400],
[0.4400, 0.5500, 0.4900, 0.4800, 0.5100, 0.4700, 0.5200],
[7.4400, 5.4200, 6.4300, 6.7600, 6.0900, 6.9300, 5.9300],
[4.7400, 6.3400, 5.5400, 5.2700, 5.8100, 5.1400, 5.9400],
[6.1500, 8.1200, 7.1400, 6.8100, 7.4600, 6.6500, 7.6300],
[3.1600, 3.7400, 3.4500, 3.3500, 3.5400, 3.3000, 3.5900],
[7.1600, 4.9400, 6.0500, 6.4200, 5.6800, 6.6100, 5.5000],
[2.8200, 7.4500, 5.1300, 4.3600, 5.9100, 3.9700, 6.2900],
[6.1900, 6.3800, 6.2900, 6.2500, 6.3200, 6.2400, 6.3400]])

In [ ]:
B

array([[4.43, 2.92, 3.68, 3.93, 3.42, 4.05, 3.3 ],
       [1.58, 1.93, 1.76, 1.7 , 1.82, 1.67, 1.84],
       [0.44, 0.55, 0.49, 0.48, 0.51, 0.47, 0.52],
       [7.44, 5.42, 6.43, 6.76, 6.09, 6.93, 5.93],
       [4.74, 6.34, 5.54, 5.27, 5.81, 5.14, 5.94],
       [6.15, 8.12, 7.14, 6.81, 7.46, 6.65, 7.63],
       [3.16, 3.74, 3.45, 3.35, 3.54, 3.3 , 3.59],
       [7.16, 4.94, 6.05, 6.42, 5.68, 6.61, 5.5 ],
       [2.82, 7.45, 5.13, 4.36, 5.91, 3.97, 6.29],
       [6.19, 6.38, 6.29, 6.25, 6.32, 6.24, 6.34]])

In [ ]:
X=B[:, [0,1,2,3,4,5]]
print(X)

[[4.43 2.92 3.68 3.93 3.42 4.05]
 [1.58 1.93 1.76 1.7  1.82 1.67]
 [0.44 0.55 0.49 0.48 0.51 0.47]
 [7.44 5.42 6.43 6.76 6.09 6.93]
 [4.74 6.34 5.54 5.27 5.81 5.14]
 [6.15 8.12 7.14 6.81 7.46 6.65]
 [3.16 3.74 3.45 3.35 3.54 3.3 ]
 [7.16 4.94 6.05 6.42 5.68 6.61]
 [2.82 7.45 5.13 4.36 5.91 3.97]
 [6.19 6.38 6.29 6.25 6.32 6.24]]


In [ ]:
y=B[:, [6]]
print(y)

[[3.3 ]
 [1.84]
 [0.52]
 [5.93]
 [5.94]
 [7.63]
 [3.59]
 [5.5 ]
 [6.29]
 [6.34]]


In [ ]:
input_data=X
output_data= y

In [ ]:
# Implement Ridge Regression.
from sklearn.linear_model import Ridge

model = Ridge(alpha=0.1)

# Fit the model to the data
model.fit(input_data, output_data)

# Predict target values for the input data
#y_pred = model.predict(x_test)
#print(y_pred)
print(model.score(input_data, output_data))

0.9999978560428622


In [ ]:
C=X.transpose()
C

array([[4.43, 1.58, 0.44, 7.44, 4.74, 6.15, 3.16, 7.16, 2.82, 6.19],
       [2.92, 1.93, 0.55, 5.42, 6.34, 8.12, 3.74, 4.94, 7.45, 6.38],
       [3.68, 1.76, 0.49, 6.43, 5.54, 7.14, 3.45, 6.05, 5.13, 6.29],
       [3.93, 1.7 , 0.48, 6.76, 5.27, 6.81, 3.35, 6.42, 4.36, 6.25],
       [3.42, 1.82, 0.51, 6.09, 5.81, 7.46, 3.54, 5.68, 5.91, 6.32],
       [4.05, 1.67, 0.47, 6.93, 5.14, 6.65, 3.3 , 6.61, 3.97, 6.24]])

In [ ]:
# D gives X transpose X
D=np.dot(C, X)
D

array([[245.4783, 244.2314, 244.9303, 244.9987, 244.6208, 245.1838],
       [244.2314, 282.6583, 263.5016, 256.9696, 269.8478, 253.8369],
       [244.9303, 263.5016, 254.2822, 251.0534, 257.2973, 249.5812],
       [244.9987, 256.9696, 251.0534, 248.9229, 252.9613, 248.0026],
       [244.6208, 269.8478, 257.2973, 252.9613, 261.4292, 250.9325],
       [245.1838, 253.8369, 249.5812, 248.0026, 250.9325, 247.3599]])

In [ ]:
E=np.identity(6)
E

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
lam=0.1
E=lam*E
E

array([[0.1, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.1, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.1, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.1, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.1, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.1]])

In [ ]:
z=D+E
z

array([[245.5783, 244.2314, 244.9303, 244.9987, 244.6208, 245.1838],
       [244.2314, 282.7583, 263.5016, 256.9696, 269.8478, 253.8369],
       [244.9303, 263.5016, 254.3822, 251.0534, 257.2973, 249.5812],
       [244.9987, 256.9696, 251.0534, 249.0229, 252.9613, 248.0026],
       [244.6208, 269.8478, 257.2973, 252.9613, 261.5292, 250.9325],
       [245.1838, 253.8369, 249.5812, 248.0026, 250.9325, 247.4599]])

In [ ]:
Inverse= np.linalg.inv(z)
Inverse

array([[ 4.88943648,  2.39681362, -1.35698973, -2.60117717, -0.09865945,
        -3.22749531],
       [ 2.39681362,  3.52414411, -2.03085651, -0.55839539, -3.51816517,
         0.18569234],
       [-1.35698973, -2.03085651,  8.29852422, -1.58193619, -1.80627503,
        -1.524934  ],
       [-2.60117717, -0.55839539, -1.58193619,  8.07362298, -1.23438631,
        -2.0940866 ],
       [-0.09865945, -3.51816517, -1.80627503, -1.23438631,  7.60923645,
        -0.95058465],
       [-3.22749531,  0.18569234, -1.524934  , -2.0940866 , -0.95058465,
         7.61198222]])

In [ ]:
X_trans_y=np.dot(C, y)
X_trans_y

array([[244.6611],
       [273.1353],
       [258.9597],
       [254.0834],
       [263.6362],
       [251.7831]])

In [ ]:
Beta= np.dot(Inverse, X_trans_y)
Beta

array([[-0.05125453],
       [ 0.42471989],
       [ 0.18631824],
       [ 0.10696734],
       [ 0.26629343],
       [ 0.06744087]])

Hence the value of ridge equation will be given by:
$y= x_0 -0.05x_1 + 0.42x_2 +0.18x_3 + 0.10x_4 +0.26x_5 +0.06x_6$