<a href="https://colab.research.google.com/github/vivek6311/Artificial-Intelligence-with-Python/blob/master/Sugarcane%20Yield%20Prediction%20using%20Least_Square_Regression_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
df= pd.read_excel("/content/NDVI_data_blocks.xlsx")
df.head()

Date     block      NDVI       CVI       EVI      EVI2       GLI  \
0 2022-02-19  Block_3A  0.327731  2.721388  0.146378  0.146378  0.042223   
1 2022-03-02  Block_3A  0.289592  2.926212  0.114807  0.114807  0.018563   
2 2022-03-09  Block_3A  0.281901  3.125308  0.101657  0.101657  0.015305   
3 2022-03-20  Block_3A  0.311678  2.833136  0.130458  0.130458  0.031863   
4 2022-03-26  Block_3A  0.304726  2.980343  0.130714  0.130714  0.012416   

      GNDVI      NDWI      SAVI  yield/acer  
0  0.396077 -0.327731  0.268570  173.165594  
1  0.394112 -0.289592  0.237335  173.165594  
2  0.404069 -0.281901  0.231034  173.165594  
3  0.397116 -0.311678  0.255439  173.165594  
4  0.404141 -0.304726  0.249742  173.165594

In [4]:
# Create dummy variables for event_type, terrain_type, and continent columns
df = pd.get_dummies(df, columns=['block'])
df.head()

Date      NDVI       CVI       EVI      EVI2       GLI     GNDVI  \
0 2022-02-19  0.327731  2.721388  0.146378  0.146378  0.042223  0.396077   
1 2022-03-02  0.289592  2.926212  0.114807  0.114807  0.018563  0.394112   
2 2022-03-09  0.281901  3.125308  0.101657  0.101657  0.015305  0.404069   
3 2022-03-20  0.311678  2.833136  0.130458  0.130458  0.031863  0.397116   
4 2022-03-26  0.304726  2.980343  0.130714  0.130714  0.012416  0.404141   

       NDWI      SAVI  yield/acer  ...  block_Block_18  block_Block_19  \
0 -0.327731  0.268570  173.165594  ...               0               0   
1 -0.289592  0.237335  173.165594  ...               0               0   
2 -0.281901  0.231034  173.165594  ...               0               0   
3 -0.311678  0.255439  173.165594  ...               0               0   
4 -0.304726  0.249742  173.165594  ...               0               0   

   block_Block_20  block_Block_26  block_Block_30b  block_Block_3A  \
0               0               0                0               1   
1               0               0                0               1   
2               0               0                0               1   
3               0               0                0               1   
4               0               0                0               1   

   block_Block_3B  block_Block_6  block_Block_7a  block_Block_7b  
0               0              0               0               0  
1               0              0               0               0  
2               0              0               0               0  
3               0              0               0               0  
4               0              0               0               0  

[5 rows x 21 columns]

In [5]:
df.columns

Index(['Date', 'NDVI', 'CVI', 'EVI', 'EVI2', 'GLI', 'GNDVI', 'NDWI', 'SAVI',
       'yield/acer', 'block_Block_15Integrated', 'block_Block_18',
       'block_Block_19', 'block_Block_20', 'block_Block_26', 'block_Block_30b',
       'block_Block_3A', 'block_Block_3B', 'block_Block_6', 'block_Block_7a',
       'block_Block_7b'],
      dtype='object')

In [6]:
X= df.drop(['Date', 'yield/acer','block_Block_7b'], axis='columns')
X.head()

NDVI       CVI       EVI      EVI2       GLI     GNDVI      NDWI  \
0  0.327731  2.721388  0.146378  0.146378  0.042223  0.396077 -0.327731   
1  0.289592  2.926212  0.114807  0.114807  0.018563  0.394112 -0.289592   
2  0.281901  3.125308  0.101657  0.101657  0.015305  0.404069 -0.281901   
3  0.311678  2.833136  0.130458  0.130458  0.031863  0.397116 -0.311678   
4  0.304726  2.980343  0.130714  0.130714  0.012416  0.404141 -0.304726   

       SAVI  block_Block_15Integrated  block_Block_18  block_Block_19  \
0  0.268570                         0               0               0   
1  0.237335                         0               0               0   
2  0.231034                         0               0               0   
3  0.255439                         0               0               0   
4  0.249742                         0               0               0   

   block_Block_20  block_Block_26  block_Block_30b  block_Block_3A  \
0               0               0                0               1   
1               0               0                0               1   
2               0               0                0               1   
3               0               0                0               1   
4               0               0                0               1   

   block_Block_3B  block_Block_6  block_Block_7a  
0               0              0               0  
1               0              0               0  
2               0              0               0  
3               0              0               0  
4               0              0               0

In [7]:
y= df['yield/acer']
y.head()

0    173.165594
1    173.165594
2    173.165594
3    173.165594
4    173.165594
Name: yield/acer, dtype: float64

In [8]:
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and fit the PLS regression model
n_components = 2  # Number of components for PLS
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, y_train)

# Predict crop yield on the testing set
y_pred = pls.predict(X_test)

# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)


Mean Squared Error (MSE): 150.70830645847215
R-squared (R2) Score: 0.8313158853899407


In [ ]:
# import pandas as pd
# from datetime import datetime

# # Load the NDVI data into a pandas dataframe
# ndvi_data = pd.read_excel('/content/NDVI_data_blocks.xlsx')  # Replace 'ndvi_data.csv' with the actual filename or path of your NDVI data

# # Convert the date column to datetime format
# ndvi_data['Date'] = pd.to_datetime(ndvi_data['Date'])

# # Calculate the mean NDVI for each date
# ndvi_data['Mean_NDVI'] = ndvi_data.iloc[:, 1:].mean(axis=1)

# # Find the peak NDVI value and corresponding date
# peak_ndvi_row = ndvi_data.loc[ndvi_data['Mean_NDVI'].idxmax()]
# peak_ndvi_date = peak_ndvi_row['Date']

# # Determine the harvesting date
# harvesting_date = peak_ndvi_date + pd.DateOffset(days=45)  # Assuming 45 days after the peak NDVI as the harvesting date

# # Print the harvesting date
# print('Harvesting Date:', harvesting_date)


In [9]:
import pandas as pd
import statsmodels.api as sm
model = sm.OLS(y, X)
results = model.fit()

# Print the regression results
print(results.summary())


                                 OLS Regression Results                                
Dep. Variable:             yield/acer   R-squared (uncentered):                   0.991
Model:                            OLS   Adj. R-squared (uncentered):              0.991
Method:                 Least Squares   F-statistic:                              2832.
Date:                Mon, 22 May 2023   Prob (F-statistic):                        0.00
Time:                        06:37:32   Log-Likelihood:                         -1835.3
No. Observations:                 440   AIC:                                      3705.
Df Residuals:                     423   BIC:                                      3774.
Df Model:                          17                                                  
Covariance Type:            nonrobust                                                  
                               coef    std err          t      P>|t|      [0.025      0.975]
---------------------------

In [11]:
print(y_pred)

[[187.85105773]
 [199.54352795]
 [132.92949434]
 [186.57132421]
 [141.9014496 ]
 [133.96161112]
 [189.97463981]
 [170.01877668]
 [128.67068194]
 [141.56675999]
 [188.10712877]
 [196.5183236 ]
 [185.15691278]
 [120.3625162 ]
 [130.55966785]
 [198.19247194]
 [129.50860023]
 [189.96188035]
 [196.63991597]
 [175.64840588]
 [179.67360979]
 [190.96457019]
 [174.34299266]
 [190.9865819 ]
 [168.77693106]
 [177.43075826]
 [196.54085186]
 [187.508783  ]
 [141.14670635]
 [190.89449281]
 [131.05189531]
 [138.20243144]
 [177.51414189]
 [111.5181111 ]
 [123.1723778 ]
 [197.47169578]
 [195.98334311]
 [170.10281952]
 [177.54461598]
 [190.52166648]
 [113.89463426]
 [176.21064373]
 [190.45564684]
 [199.7497082 ]
 [177.12976928]
 [172.93089936]
 [192.03687839]
 [129.71247703]
 [198.84603111]
 [116.90966152]
 [116.08067308]
 [168.82904052]
 [176.75183049]
 [177.12306228]
 [185.06392572]
 [172.98999093]
 [142.26386919]
 [133.26160012]
 [193.4388516 ]
 [128.98224742]
 [176.25643067]
 [166.51763455]
 [134.51

In [13]:
X = df[['NDVI', 'CVI', 'EVI', 'EVI2', 'GLI', 'GNDVI', 'NDWI', 'SAVI']]
y=df['yield/acer']

In [14]:
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and fit the PLS regression model
n_components = 2  # Number of components for PLS
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, y_train)

# Predict crop yield on the testing set
y_pred = pls.predict(X_test)

# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)


Mean Squared Error (MSE): 649.2510091269173
R-squared (R2) Score: 0.27330925409582874


In [15]:
import pandas as pd
import statsmodels.api as sm
model = sm.OLS(y, X)
results = model.fit()

# Print the regression results
print(results.summary())


                                 OLS Regression Results                                
Dep. Variable:             yield/acer   R-squared (uncentered):                   0.970
Model:                            OLS   Adj. R-squared (uncentered):              0.969
Method:                 Least Squares   F-statistic:                              1971.
Date:                Mon, 22 May 2023   Prob (F-statistic):                   9.88e-324
Time:                        06:38:59   Log-Likelihood:                         -2110.5
No. Observations:                 440   AIC:                                      4235.
Df Residuals:                     433   BIC:                                      4264.
Df Model:                           7                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [16]:
print(y_pred)

[[155.11285404]
 [155.02021971]
 [159.96048415]
 [173.93776899]
 [155.54376863]
 [165.5387951 ]
 [187.5669386 ]
 [183.29315289]
 [135.71695215]
 [143.88457944]
 [173.32192511]
 [169.13840117]
 [179.05283692]
 [151.70069005]
 [105.87230799]
 [167.11546283]
 [142.64136037]
 [194.20641241]
 [171.14296145]
 [181.59337223]
 [173.32454403]
 [213.4940554 ]
 [145.21827652]
 [181.37405221]
 [170.31798496]
 [181.95583794]
 [139.1255309 ]
 [169.81378728]
 [133.84436047]
 [174.5636768 ]
 [159.77049945]
 [154.50189486]
 [172.53556134]
 [165.59720028]
 [158.95927183]
 [152.26233857]
 [167.88976728]
 [168.14763391]
 [151.69911689]
 [161.67111735]
 [156.1675261 ]
 [182.77032322]
 [172.51606657]
 [147.92989234]
 [175.86604685]
 [176.16485673]
 [182.97917543]
 [164.8510533 ]
 [151.61388598]
 [151.25673555]
 [153.74904852]
 [180.83070388]
 [181.47109433]
 [177.64960492]
 [163.53743881]
 [158.89577306]
 [164.62433958]
 [175.39474573]
 [183.92856929]
 [120.97539794]
 [177.60232457]
 [180.44971209]
 [177.14

# Partial Least Square Regression on Individual Parameters

In [20]:
import pandas as pd
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# Separate X and Y variables
X = df['NDVI'].values.reshape(-1, 1)  # Reshape X to a 2D array
Y = df['yield/acer'].values.reshape(-1, 1)  # Reshape Y to a 2D array

# Scale the X and Y variables
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
Y_scaled = scaler.fit_transform(Y)

# Split the data into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y_scaled, test_size=0.2, random_state=42)

# Perform PLS regression
n_components = 1  # Number of PLS components
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, Y_train)

# Predict on the test set
Y_pred = pls.predict(X_test)

# Inverse scale the predicted values
Y_pred_inverse = scaler.inverse_transform(Y_pred)

# Print the predicted values
print("Predicted values:")
print(Y_pred_inverse)


Predicted values:
[[166.63269367]
 [164.77515774]
 [165.97339715]
 [170.21438427]
 [162.73336681]
 [165.54971441]
 [165.82227839]
 [165.8320059 ]
 [162.58817598]
 [157.88162803]
 [166.33773686]
 [165.11666028]
 [169.72662386]
 [164.3935207 ]
 [164.56565273]
 [165.33381928]
 [162.15512967]
 [165.74407051]
 [166.54011608]
 [162.5201128 ]
 [162.96451316]
 [169.99743572]
 [165.76390347]
 [165.1519736 ]
 [167.81807695]
 [164.37103603]
 [166.24464278]
 [167.81199183]
 [157.76405557]
 [170.85284707]
 [166.45806091]
 [164.56106617]
 [162.14642445]
 [170.77868562]
 [163.5997133 ]
 [166.06293386]
 [161.45840266]
 [167.94538096]
 [164.47755694]
 [164.88347073]
 [168.60594517]
 [163.97894692]
 [166.35373378]
 [164.94871855]
 [160.42530896]
 [166.10426417]
 [165.83529854]
 [166.9166604 ]
 [165.04257267]
 [166.75913712]
 [165.90460416]
 [171.35232837]
 [164.95768208]
 [161.08090708]
 [160.03015943]
 [167.10718936]
 [160.15332565]
 [166.50378429]
 [172.16103081]
 [165.08190335]
 [164.38620876]
 [169.

In [21]:
# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)

Mean Squared Error (MSE): 649.2510091269173
R-squared (R2) Score: 0.27330925409582874


# On CVI

In [22]:
#X = df[ 'CVI'] #, 'EVI', 'EVI2', 'GLI', 'GNDVI', 'NDWI', 'SAVI'
# Separate X and Y variables
X = df['CVI'].values.reshape(-1, 1)  # Reshape X to a 2D array
Y = df['yield/acer'].values.reshape(-1, 1)  # Reshape Y to a 2D array

# Scale the X and Y variables
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
Y_scaled = scaler.fit_transform(Y)

# Split the data into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y_scaled, test_size=0.2, random_state=42)

# Perform PLS regression
n_components = 1  # Number of PLS components
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, Y_train)

# Predict on the test set
Y_pred = pls.predict(X_test)

# Inverse scale the predicted values
Y_pred_inverse = scaler.inverse_transform(Y_pred)

# Print the predicted values
print("Predicted values:")
print(Y_pred_inverse)


Predicted values:
[[165.26124564]
 [164.65757641]
 [167.37149738]
 [166.51700423]
 [164.20485189]
 [165.5030458 ]
 [164.5499676 ]
 [167.80593091]
 [162.33192692]
 [160.8203615 ]
 [166.75594714]
 [168.12724491]
 [167.42340603]
 [164.80336575]
 [161.91087725]
 [166.78162458]
 [163.28159924]
 [165.53109365]
 [167.43530719]
 [164.97595021]
 [166.12192518]
 [166.83828722]
 [163.35388249]
 [163.23985716]
 [165.64207107]
 [163.5615761 ]
 [163.0707325 ]
 [165.80825266]
 [159.62369267]
 [168.33959784]
 [165.74278402]
 [164.73439275]
 [162.7163756 ]
 [167.08232163]
 [164.87801814]
 [164.57435421]
 [164.22647044]
 [164.53925151]
 [163.27677863]
 [164.52059383]
 [165.96912629]
 [164.45630996]
 [165.34134224]
 [163.40367127]
 [163.86800182]
 [168.3798489 ]
 [162.73461281]
 [166.93936777]
 [164.37781009]
 [164.93003919]
 [166.36112477]
 [168.26849499]
 [163.71836645]
 [163.95710435]
 [163.46362277]
 [165.28934514]
 [163.96955089]
 [166.74574461]
 [167.48806668]
 [162.07964804]
 [163.57754434]
 [167.

In [23]:
# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)

Mean Squared Error (MSE): 649.2510091269173
R-squared (R2) Score: 0.27330925409582874


# EVI

In [24]:
#X = df[ 'CVI'] #, 'EVI', 'EVI2', 'GLI', 'GNDVI', 'NDWI', 'SAVI'
# Separate X and Y variables
X = df['EVI'].values.reshape(-1, 1)  # Reshape X to a 2D array
Y = df['yield/acer'].values.reshape(-1, 1)  # Reshape Y to a 2D array

# Scale the X and Y variables
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
Y_scaled = scaler.fit_transform(Y)

# Split the data into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y_scaled, test_size=0.2, random_state=42)

# Perform PLS regression
n_components = 1  # Number of PLS components
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, Y_train)

# Predict on the test set
Y_pred = pls.predict(X_test)

# Inverse scale the predicted values
Y_pred_inverse = scaler.inverse_transform(Y_pred)

# Print the predicted values
print("Predicted values:")
print(Y_pred_inverse)
# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)

Predicted values:
[[159.0787635 ]
 [162.4685722 ]
 [163.09969951]
 [160.76611209]
 [166.76877526]
 [164.42128977]
 [167.57445332]
 [168.18053987]
 [162.71174236]
 [171.16002697]
 [164.77770472]
 [165.76191725]
 [161.50674546]
 [162.7008869 ]
 [144.03741042]
 [165.46590995]
 [165.32839834]
 [169.60366874]
 [165.16431495]
 [170.92198631]
 [170.21724981]
 [167.99149322]
 [156.73826123]
 [167.14086925]
 [161.46775283]
 [169.02461726]
 [154.62216491]
 [161.740465  ]
 [168.68074671]
 [159.69902022]
 [160.60615513]
 [164.05566063]
 [169.5997226 ]
 [158.68438737]
 [166.49142209]
 [159.67228563]
 [170.60234333]
 [161.02809121]
 [161.43327795]
 [163.37100479]
 [158.75549998]
 [169.40931943]
 [165.2661372 ]
 [160.05058479]
 [172.69403677]
 [166.24470323]
 [166.94176666]
 [161.407594  ]
 [160.8128542 ]
 [159.69598372]
 [160.86204497]
 [160.04956735]
 [167.73755896]
 [172.30118825]
 [171.67799621]
 [159.5227673 ]
 [171.59029292]
 [166.26133981]
 [160.82123588]
 [147.41967422]
 [167.24637593]
 [161.

#EVI2

In [25]:
#X = df[ 'CVI'] #, 'EVI', 'EVI2', 'GLI', 'GNDVI', 'NDWI', 'SAVI'
# Separate X and Y variables
X = df['EVI2'].values.reshape(-1, 1)  # Reshape X to a 2D array
Y = df['yield/acer'].values.reshape(-1, 1)  # Reshape Y to a 2D array

# Scale the X and Y variables
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
Y_scaled = scaler.fit_transform(Y)

# Split the data into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y_scaled, test_size=0.2, random_state=42)

# Perform PLS regression
n_components = 1  # Number of PLS components
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, Y_train)

# Predict on the test set
Y_pred = pls.predict(X_test)

# Inverse scale the predicted values
Y_pred_inverse = scaler.inverse_transform(Y_pred)

# Print the predicted values
print("Predicted values:")
print(Y_pred_inverse)
# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)

Predicted values:
[[159.0787635 ]
 [162.4685722 ]
 [163.09969951]
 [160.76611209]
 [166.76877526]
 [164.42128977]
 [167.57445332]
 [168.18053987]
 [162.71174236]
 [171.16002697]
 [164.77770472]
 [165.76191725]
 [161.50674546]
 [162.7008869 ]
 [144.03741042]
 [165.46590995]
 [165.32839834]
 [169.60366874]
 [165.16431495]
 [170.92198631]
 [170.21724981]
 [167.99149322]
 [156.73826123]
 [167.14086925]
 [161.46775283]
 [169.02461726]
 [154.62216491]
 [161.740465  ]
 [168.68074671]
 [159.69902022]
 [160.60615513]
 [164.05566063]
 [169.5997226 ]
 [158.68438737]
 [166.49142209]
 [159.67228563]
 [170.60234333]
 [161.02809121]
 [161.43327795]
 [163.37100479]
 [158.75549998]
 [169.40931943]
 [165.2661372 ]
 [160.05058479]
 [172.69403677]
 [166.24470323]
 [166.94176666]
 [161.407594  ]
 [160.8128542 ]
 [159.69598372]
 [160.86204497]
 [160.04956735]
 [167.73755896]
 [172.30118825]
 [171.67799621]
 [159.5227673 ]
 [171.59029292]
 [166.26133981]
 [160.82123588]
 [147.41967422]
 [167.24637593]
 [161.

# GLI

In [26]:
#X = df[ 'CVI'] #, 'EVI', 'EVI2', 'GLI', 'GNDVI', 'NDWI', 'SAVI'
# Separate X and Y variables
X = df['GLI'].values.reshape(-1, 1)  # Reshape X to a 2D array
Y = df['yield/acer'].values.reshape(-1, 1)  # Reshape Y to a 2D array

# Scale the X and Y variables
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
Y_scaled = scaler.fit_transform(Y)

# Split the data into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y_scaled, test_size=0.2, random_state=42)

# Perform PLS regression
n_components = 1  # Number of PLS components
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, Y_train)

# Predict on the test set
Y_pred = pls.predict(X_test)

# Inverse scale the predicted values
Y_pred_inverse = scaler.inverse_transform(Y_pred)

# Print the predicted values
print("Predicted values:")
print(Y_pred_inverse)
# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)

Predicted values:
[[164.64891984]
 [164.29150012]
 [164.4850349 ]
 [167.03488106]
 [164.07012071]
 [164.6333394 ]
 [164.85353631]
 [165.05999816]
 [164.34612291]
 [163.87068188]
 [164.75483548]
 [164.12765733]
 [166.29831172]
 [164.18074104]
 [164.31534751]
 [164.5114524 ]
 [164.21747273]
 [165.12755646]
 [165.10176738]
 [163.87478416]
 [164.37509557]
 [167.66075904]
 [164.62539101]
 [164.82249633]
 [165.30489013]
 [164.77222984]
 [164.88257695]
 [165.36185489]
 [164.20440712]
 [167.12927355]
 [164.55975183]
 [164.47876302]
 [164.04843477]
 [167.37024433]
 [164.33851797]
 [164.69165089]
 [163.94161225]
 [165.61438891]
 [164.41751682]
 [164.33463529]
 [165.81885933]
 [164.38403615]
 [165.23952731]
 [164.52422853]
 [163.6520042 ]
 [164.72624254]
 [165.33584582]
 [164.60871384]
 [164.37735307]
 [165.06471345]
 [164.33374043]
 [167.52981566]
 [164.75495336]
 [163.88327076]
 [163.80020591]
 [165.01288153]
 [163.65823134]
 [165.38916598]
 [169.52467041]
 [164.42201724]
 [164.42942162]
 [166.

# GNDVI

In [27]:
#X = df[ 'CVI'] #, 'EVI', 'EVI2', 'GLI', 'GNDVI', 'NDWI', 'SAVI'
# Separate X and Y variables
X = df['GNDVI'].values.reshape(-1, 1)  # Reshape X to a 2D array
Y = df['yield/acer'].values.reshape(-1, 1)  # Reshape Y to a 2D array

# Scale the X and Y variables
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
Y_scaled = scaler.fit_transform(Y)

# Split the data into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y_scaled, test_size=0.2, random_state=42)

# Perform PLS regression
n_components = 1  # Number of PLS components
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, Y_train)

# Predict on the test set
Y_pred = pls.predict(X_test)

# Inverse scale the predicted values
Y_pred_inverse = scaler.inverse_transform(Y_pred)

# Print the predicted values
print("Predicted values:")
print(Y_pred_inverse)
# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)

Predicted values:
[[166.75725066]
 [164.74467132]
 [167.1552162 ]
 [171.00311834]
 [162.75200087]
 [165.89456266]
 [165.62389572]
 [167.24776127]
 [161.19029702]
 [155.33541098]
 [167.21557467]
 [166.73987082]
 [170.7745026 ]
 [164.50227832]
 [162.62350559]
 [166.33652068]
 [161.36357805]
 [166.10095058]
 [167.67310988]
 [163.05440506]
 [164.07337537]
 [170.87333949]
 [164.81597564]
 [164.18798698]
 [168.06851788]
 [163.69375588]
 [165.09135736]
 [168.15196043]
 [152.98605476]
 [172.38473699]
 [166.80271547]
 [164.61143125]
 [161.12351343]
 [171.86864526]
 [163.91128883]
 [165.86126411]
 [161.70761319]
 [167.65845718]
 [163.60163083]
 [164.77145928]
 [169.01104474]
 [163.92358646]
 [166.53442198]
 [164.09988329]
 [160.62130814]
 [167.67131694]
 [164.39614622]
 [167.77901108]
 [164.80374939]
 [166.68490329]
 [166.63937437]
 [172.96294382]
 [164.31407711]
 [161.17013589]
 [159.99127368]
 [167.21307129]
 [160.48619143]
 [167.35576491]
 [173.84458598]
 [163.24156931]
 [163.69875744]
 [170.

# NDWI

In [28]:
#X = df[ 'CVI'] #, 'EVI', 'EVI2', 'GLI', 'GNDVI', 'NDWI', 'SAVI'
# Separate X and Y variables
X = df['NDWI'].values.reshape(-1, 1)  # Reshape X to a 2D array
Y = df['yield/acer'].values.reshape(-1, 1)  # Reshape Y to a 2D array

# Scale the X and Y variables
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
Y_scaled = scaler.fit_transform(Y)

# Split the data into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y_scaled, test_size=0.2, random_state=42)

# Perform PLS regression
n_components = 1  # Number of PLS components
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, Y_train)

# Predict on the test set
Y_pred = pls.predict(X_test)

# Inverse scale the predicted values
Y_pred_inverse = scaler.inverse_transform(Y_pred)

# Print the predicted values
print("Predicted values:")
print(Y_pred_inverse)
# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)

Predicted values:
[[166.63269367]
 [164.77515774]
 [165.97339715]
 [170.21438427]
 [162.73336681]
 [165.54971442]
 [165.82227839]
 [165.8320059 ]
 [162.58817597]
 [157.88162804]
 [166.33773686]
 [165.11666028]
 [169.72662384]
 [164.3935207 ]
 [164.56565273]
 [165.33381928]
 [162.15512968]
 [165.74407051]
 [166.54011608]
 [162.52011281]
 [162.96451316]
 [169.99743572]
 [165.76390346]
 [165.1519736 ]
 [167.81807695]
 [164.37103603]
 [166.24464278]
 [167.81199184]
 [157.76405559]
 [170.85284706]
 [166.45806091]
 [164.56106617]
 [162.14642445]
 [170.77868562]
 [163.5997133 ]
 [166.06293386]
 [161.45840266]
 [167.94538095]
 [164.47755694]
 [164.88347073]
 [168.60594517]
 [163.97894692]
 [166.35373377]
 [164.94871855]
 [160.42530896]
 [166.10426417]
 [165.83529854]
 [166.91666039]
 [165.04257267]
 [166.75913712]
 [165.90460416]
 [171.35232836]
 [164.95768208]
 [161.08090708]
 [160.03015944]
 [167.10718936]
 [160.15332565]
 [166.50378428]
 [172.1610308 ]
 [165.08190334]
 [164.38620876]
 [169.

# SAVI

In [29]:
#X = df[ 'CVI'] #, 'EVI', 'EVI2', 'GLI', 'GNDVI', 'NDWI', 'SAVI'
# Separate X and Y variables
X = df['SAVI'].values.reshape(-1, 1)  # Reshape X to a 2D array
Y = df['yield/acer'].values.reshape(-1, 1)  # Reshape Y to a 2D array

# Scale the X and Y variables
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
Y_scaled = scaler.fit_transform(Y)

# Split the data into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y_scaled, test_size=0.2, random_state=42)

# Perform PLS regression
n_components = 1  # Number of PLS components
pls = PLSRegression(n_components=n_components)
pls.fit(X_train, Y_train)

# Predict on the test set
Y_pred = pls.predict(X_test)

# Inverse scale the predicted values
Y_pred_inverse = scaler.inverse_transform(Y_pred)

# Print the predicted values
print("Predicted values:")
print(Y_pred_inverse)
# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)

Predicted values:
[[159.44258417]
 [163.13618131]
 [157.30752088]
 [150.61346623]
 [166.21952851]
 [162.7542243 ]
 [172.35938225]
 [164.48128467]
 [162.2457313 ]
 [177.30589188]
 [162.4979806 ]
 [162.2689487 ]
 [154.72853923]
 [162.10381011]
 [161.17914626]
 [161.7184042 ]
 [163.6321319 ]
 [172.48651917]
 [158.6551514 ]
 [177.00023081]
 [168.9619172 ]
 [165.58084071]
 [162.19560449]
 [173.44778003]
 [160.05379381]
 [173.85701916]
 [159.40427132]
 [159.11856392]
 [177.68262344]
 [147.70259011]
 [160.56282361]
 [161.19106301]
 [177.63532116]
 [144.78420395]
 [164.25459   ]
 [159.8666056 ]
 [173.68183306]
 [159.76967326]
 [165.30544683]
 [165.83170033]
 [150.67757824]
 [174.5225088 ]
 [162.46168005]
 [162.69503575]
 [180.55683726]
 [161.3737886 ]
 [172.33810033]
 [159.45564042]
 [162.45765771]
 [155.68651537]
 [158.0046085 ]
 [148.68421639]
 [172.86203541]
 [179.44333787]
 [176.05717016]
 [158.94735208]
 [175.78269815]
 [160.45122283]
 [144.38279274]
 [163.88413387]
 [173.83237268]
 [155.