<a href="https://colab.research.google.com/github/vivek6311/Artificial-Intelligence-with-Python/blob/master/Vivek_Kumar_TLP23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programming Test `Instructions`

---
### <u>Due date:</u> 28.11.2022

### <u>Important remarks: </u>

1. All of your functions have to **return** the desired values. Do not use a print statement instead of a return statement. Please delete all print statements from your functions before submitting your notebook.
2. **Do not rename your functions!** We will only grade functions with the original name.
3. Do not use Python's `input()` function. Code cells containing the `input()` function will not be graded.
4. Before submitting the notebook, please make sure that the code cells in which you define the functions can be executed without errors.

### <u>How to submit: </u>

1. Solve the tasks *in a copy of this notebook* and save your edited Notebook as an .ipynb file
2. Rename the edited Notebook according to the naming convention stated below!
3. Upload the Jupyter Notebook to this course Brightspace assignment module.

### <u>Regarding the evaluation: </u>
1. The evaluation of your submission is partially automated. Therefore, it is important that you solve the tasks according to the instructions.
2. Your functions will be evaluated using tests (unknown to you). These tests are similar to the test cases provided under each task, but differ in the function arguments. Make sure that your functions pass our test cases. These are a good indicator for passing the further tests.
3. For a final check, you should do the following: Click "Runtime"/"Kernel" in the toolbar and select the "Restart and run all" option. Then take another look at the self-tests and check if they return True.

It is **important** that you name the edited Jupyter Notebook files you want to upload (file identifier ".ipynb") according to a specific naming convention! If the naming is incorrect, we will not be able to record your submission with regard to your required efforts.

Therefore please name your upload as follows:  
> Firstname_Lastname_TLP23.ipynb  
> e.g. Joseph_Thachil_TLP23.ipynb

# 1. What is my grade? [10 points]

---

Let's assume that, after finishing your study program at Plaksha, you join another university that wants to give letter grades in the future. You are asked to write a small program that turns a score into a grade.

**Task:** Write a function that takes the achieved percentage of an exam (a float or integer value) and **returns** the corresponding grade (a string value). Possible grades are `'A'`, `'B'`, `'C'`, `'D'`, `'E'`, and `'F'`. Letter grades are associated with scores as follows:
* A: $\geq$ 90 
* B: $<$ 90 and $\geq$ 80 
* C: $<$ 80 and $\geq$ 70 
* D: $<$ 70 and $\geq$ 60 
* E: $<$ 60 and $\geq$ 50 
* F: $<$ 50 

In [ ]:
def grade(score):
  if score>=90:
    return 'A'
  elif score>=80 and score<90:
    return 'B'
  elif score>=70 and score<80:
    return 'C'
  elif score>=60 and score<70:
    return 'D'
  elif score>=50 and score<60:
    return 'E'
  else:
    return 'F'
    
    pass

In [ ]:
print(grade(70.5) == 'C')   # should print True
print(grade(90) == 'A')     # should print True
print(grade(50) == 'E')     # should print True

True
True
True


# 2. Classifying wrenches [10 points]
---

You work at a company that produces three different wrenches ("Type A", "Type B", and "Type C"). A sensor can measure the length and width of each wrench. Now, you are asked to implement a function that classifies each wrench based on its length (a float value in mm) and width (float value in mm) according to the following rules:

- Type A: $40$ mm $\leq$ length $\leq 50$ mm *and*  $9$ mm $\leq$ width $\leq 12$ mm 
- Type B: $58$ mm $\leq$ length $\leq 60$ mm *and* $11$ mm $\leq$ width $\leq 13$ mm 
- Type C: $58$ mm $\leq$ length $\leq 60$ mm *and* $16$ mm $\leq$ width $\leq 18$ mm 
- Production failure in any other case 

The function should return a string that specifies the type. For instance, if you pass the arguments 58 and 12 to your function, the return value should be 'Type B'. In case of a production failure, the function shall return 'Production failure'

In [ ]:
def classify_wrenches(length, width):
  if 40 <=length <=50 and 9<= width <=12:
    return "Type A"
  elif 58 <=length <=60 and 11<= width <=13:
    return "Type B"
  elif 58 <=length <=60 and 16<= width <=18:
    return "Type C"
  else:
    return "Production failure"
  pass     

In [ ]:
print(classify_wrenches(60.1, 17.0) == 'Production failure') # should print True
print(classify_wrenches(59.3, 18.0) == 'Type C')             # should print True

True
True


# 3. Overtime [10 points]

---

You work in the finance department of a small company. At the end of the week, salary transfers are due again. Unfortunately, the company servers have an error that causes overtime to be paid incorrectly. It is now your task to determine the correct weekly salary.

**Task:** Write a function that takes a person's weekly work hours (a float value) as well as their regular hourly rate (a float value). **Return** a person's total pay for the week (a float value), considering overtime hours. 

Every hour worked over $40$ is considered overtime and compensated at $1.4$ times the rate of normal pay. However, if a person works **more than** $50$ hours, they will receive double their hourly wage. Therefore, they are paid at $1.4$ times the normal rate for a maximum of $10$ hours of overtime and *double* ($2.0$ times) the normal rate thereafter. 

In [ ]:
def overtime(working_hours, hourly_rate):
  salary=0
  if working_hours<=40:
    salary=working_hours * hourly_rate
    return salary
  elif 40<= working_hours<=50:
    salary= (salary +(working_hours -40)* (1.4* hourly_rate))
    return salary
  else:
    salary= (salary +(working_hours -40)* (2* hourly_rate))
    return salary
    pass

In [ ]:
print(overtime(65.0, 16.5) == 1386.0)   # should print True
print(overtime(35.0, 12.0) == 420.0)    # should print True

False
True


# 4. List vs Tuple [10 points]

---

Instantiate a list of 5 real number. Instantiate a tuple of 5 real numbers. What is the difference between the two - demonstrate programmatically.

In [ ]:
# Instantiate list
l=[1,2,3,4,5]
# Instantiate tuple
T=(6, 7,8,10,11)

The contents of a tuple cannot change once they have been created where as we can add/ modify the values in the list.

In [ ]:
# write a short comment and demonstrate programmatically
l=l.insert(12)
#The contents of a tuple cannot change once they have been created where as we can

# 5. Python 101 [10 points]

---

Instantiate a variable 'alpha' to take integer value 10. Then, pass the 

1.   List item

1.   List item
2.   List item


2.   List item

character 'a' to this variable. Then pass the boolean value True to it. 

Do you get any error passing different data types to 'alpha'? Why or Why not? 
What is this feature of python called? And what is the high-level code to machine code translation paradigm of python that enables this?

In [ ]:
alpha=int(10)
alpha= str('a')
alpha= True


I did not got any error while passing different value to the alpha. 

# 6. Fibonacci [10 points]

---

In a remote island off the coast of India, a scientist finds a connection between the average number of rabbits in each successive generation and the Fibonnaci series. Write for him a generator function that can be called with **the starting index and the number of elements desired** for a Fibonacci series.

In [ ]:
def fibonacci(index, num):
    # Remove the pass and write your code here
    for i in range(num):
        yield num
        index,num= num,index+ num
    pass

In [ ]:
print(list(fibonacci(0,5))==[0, 1, 1, 2, 3])
print(list(fibonacci(5,5))==[5, 8, 13, 21, 34])

False
False


# 7. One-Liner [10 points]

---

Create a one line code to implement x^2-2x on a predefined list of positive integers and return as list

In [ ]:
# define list
lis = [1,2,3,4]

# your code here
def square(x):
	return  (x*x)
sqr_iter = map(square, lis)
squared_numbers = list(sqr_iter)
#print(squared_numbers) 

[1, 4, 9, 16]


# 8. Matrix [10 points]

---

We have a huge 12x12 matrix defined. We would like to multiply this with a 3x2 kernel matrix in a block by block manner (with 3x3 sub matrices of the 12x12 matrix, without any overlap), as compression strategy. Write a piece of code to take inputs of the above size and return a 12x8 matrix.
What would you change if a third dimension was added to the big matrix: it is now of size 12x12x3.

In [ ]:
import numpy as np

np.random.seed(0)
array = np.random.randint(10, size=(12, 12))
print(array)
kernel = np.random.randint(10, size=(3, 2))
print(kernel)

def compress(array, kernel):
  compressed_arr = np.tensordot(array,kernel,([12,12],[3,2]))


[[5 0 3 3 7 9 3 5 2 4 7 6]
 [8 8 1 6 7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3 8 1 3 3]
 [3 7 0 1 9 9 0 4 7 3 2 7]
 [2 0 0 4 5 5 6 8 4 1 4 9]
 [8 1 1 7 9 9 3 6 7 2 0 3]
 [5 9 4 4 6 4 4 3 4 4 8 4]
 [3 7 5 5 0 1 5 9 3 0 5 0]
 [1 2 4 2 0 3 2 0 7 5 9 0]
 [2 7 2 9 2 3 3 2 3 4 1 2]
 [9 1 4 6 8 2 3 0 0 6 0 6]
 [3 3 8 8 8 2 3 2 0 8 8 3]]
[[8 2]
 [8 4]
 [3 0]]


In [ ]:
compressed_arr = compress(array, kernel)
print(compressed_arr.shape == (12, 8))

IndexError: ignored

# 9. Sort this out [10 points]

---

a) Define a 'sorted_list' class as an abstract class.

b) Inherit this into a child class that executes a vanilla sorting algorithm on the list is it intialised with.

c) We want this class to provide meta-analytics such as the time and space taken to sort the list. Can you add those as functions to this class.

d) Having noted the space and time taken on a list of 10000 elements - we were disconcerted - it takes too long and is memory guzzling. Can we create a new class to override the vanilla sorting algorithm.

e) Show programmatically on a list of length 10000 that this new sorting algorithm is better.

f) Use this to run the function for comparing the performance at the script call (__name__ == main)